version: "3.5"
networks:
  portal-link:
     external: true
  mini-web:
services:
  edif-dash:
    build: dashboard
    networks:
      - portal-link
      - mini-web

    restart: on-failure
    volumes:
      - .env:/env/.env
      - ./cached/:/cached/
      - ./python_lib:/usr/local/lib/python3.9/site-packages/dash_data

  edif-cacher:
    build: python_cacher
    networks:
      - portal-link
    restart: on-failure
    volumes:
      - .env:/env/.env
      - ./cached/:/cached/
      - ./python_lib:/usr/local/lib/python3.9/site-packages/dash_data
