version: '3.8'
services:
  edif-cache:
    image: redis:6.2-alpine
    restart: always
  edif-dash:
    build: dashboard

    restart: on-failure
    ports:
      - 8080:80
    volumes:
      - .env:/env/.env