version: '3.8'
services:
  edif-cache:
    image: redis:6.2-alpine
    restart: always
  edif-dash:
    build: dashboard

    restart: on-failure
    ports:
      - 8080:80
    volumes:
      - .env:/env/.env
      - ./cached/:/cached/
      - ./python_lib:/usr/local/lib/python3.9/site-packages/dash_data

  edif-cacher:
    build: python_cacher

    restart: on-failure
    volumes:
      - .env:/env/.env
      - ./cached/:/cached/
      - ./python_lib:/usr/local/lib/python3.9/site-packages/dash_data
